# Generated by Django 6.0.4 on 2026-05-12 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('single', 'Single'), ('double', 'Double'), ('suite', 'Suite')], max_length=10)),
                ('room_name', models.CharField(max_length=100)),
                ('room_description', models.TextField()),
                ('beds', models.IntegerField()),
                ('max_guests', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('capacity', models.IntegerField()),
                ('image_url', models.URLField(blank=True, null=True)),
                ('available', models.BooleanField(default=True)),
                ('amenities', models.ManyToManyField(to='base.amenity')),
            ],
        ),
    ]
