# Generated by Django 6.0.4 on 2026-05-12 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('single', 'Single'), ('double', 'Double'), ('suite', 'Suite'), ('Royal Nordic Suite', 'Royal Nordic Suite'), ('Presidential Suite', 'Presidential Suite'), ('Fjord Panorama Suite', 'Fjord Panorama Suite'), ('Nordic Deluxe Room', 'Nordic Deluxe Room'), ('Scandinavian Comfort Room', 'Scandinavian Comfort Room'), ('Arctic Explorer Suite', 'Arctic Explorer Suite'), ('Viking Heritage Room', 'Viking Heritage Room')], max_length=50),
        ),
    ]
